/**
 * Followed shows from TV Time GDPR export.
 * Source: user_tv_show_data.csv (is_followed=1) — the authoritative list.
 * Embedded for offline/filesystem usage — no server required.
 *
 * DATA VERSION: bump when shows change to bust stale caches.
 */
var TVTIME_DATA_VERSION = 5;

var FOLLOWED_SHOWS = [
  "3 Body Problem",
  "Ahsoka",
  "Altered Carbon",
  "American Primeval",
  "Andor",
  "Avenue 5",
  "Away",
  "Billions",
  "Brilliant Minds",
  "Chad Powers",
  "Dune: Prophecy",
  "Earth Abides",
  "Echo 3",
  "Fallout",
  "Foundation (2021)",
  "Game of Thrones",
  "Gold Rush",
  "Gold Rush: Dave Turin's Lost Mine",
  "Halo",
  "Hawkeye (2021)",
  "Homestead: The Series",
  "House of the Dragon",
  "Ironheart",
  "Jupiter's Legacy",
  "Lioness",
  "Loki",
  "Madam Secretary",
  "Masters of the Air",
  "Moonhaven",
  "Murderbot",
  "New Amsterdam (2018)",
  "Obi-Wan Kenobi",
  "Outer Banks",
  "Paradise (2025)",
  "Percy Jackson and the Olympians",
  "PLUR1BUS",
  "Prime Target",
  "Rabbit Hole",
  "Raised by Wolves (2020)",
  "Reacher",
  "Scrubs (2026)",
  "SEAL Team",
  "See",
  "Shark Tank",
  "She-Hulk: Attorney at Law",
  "Shōgun",
  "Silicon Valley",
  "Silo",
  "Snowpiercer",
  "Space Force",
  "Star Trek: Discovery",
  "Star Trek: Picard",
  "Star Trek: Starfleet Academy",
  "Star Trek: Strange New Worlds",
  "Star Wars: Skeleton Crew",
  "Stick",
  "Suits LA",
  "Superman & Lois",
  "Tehran",
  "The Acolyte",
  "The Book of Boba Fett",
  "The Copenhagen Test",
  "The Day of the Jackal",
  "The Diplomat",
  "The Elon Musk Show",
  "The Endgame",
  "The Falcon and The Winter Soldier",
  "The Gentlemen",
  "The Gilded Age",
  "The Good Doctor",
  "The Last of Us",
  "The Line",
  "The Lord of the Rings: The Rings of Power",
  "The Mandalorian",
  "The Nevers",
  "The Night Agent",
  "The Orville",
  "The Pendragon Cycle: Rise of the Merlin",
  "The Peripheral",
  "The Pitt",
  "The Rainmaker",
  "The Terminal List: Dark Wolf",
  "The Umbrella Academy",
  "The War Between the Land and the Sea",
  "The Wheel of Time",
  "The Witcher",
  "Tom Clancy's Jack Ryan",
  "Treadstone",
  "WandaVision",
  "Warrior Nun",
  "White House Plumbers",
  "Your Honor"
];
